spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect


spotify:
  client-id: 00094ebdc44a465ca28bc5eb31a3e46f
  client-secret: de558f980a7b4805add7f6f00f0913aa